#!/bin/bash

php runweekly.php

cd ../public/dati

zip -X categorie.zip licenza.txt categorie.csv
zip -z categorie.zip < licenza.txt
rm -f categorie.csv

zip -X target.zip licenza.txt target.csv
zip -z target.zip < licenza.txt
rm -f target.csv

zip -X dns.zip licenza.txt dns.csv
zip -z dns.zip < licenza.txt
rm -f dns.csv

zip -X generator.zip licenza.txt generator.csv
zip -z generator.zip < licenza.txt
rm -f generator.csv

zip -X header.zip licenza.txt header.csv
zip -z header.zip < licenza.txt
rm -f header.csv

zip -X httpserver.zip licenza.txt httpserver.csv
zip -z httpserver.zip < licenza.txt
rm -f httpserver.csv
